spring:
  datasource:
    url: jdbc:h2:./testdb;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create
#  session:
#    timeout: 1
# you can also use 'update' instead of 'create-drop'

logger:
  level:
    org.optaplanner: TRACE
    org.hibernate.SQL: TRACE
    ch.uzh.ifi.seal: DEBUG