package ch.uzh.ifi.seal.domain_classes;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.google.common.base.Objects;

import javax.persistence.*;
import java.time.LocalDate;

/**
 * Keeps the information that user is entering into the daily form,
 * like the sleep duration, quality of sleep and the stress level.
 * <p>
 * Is entity managed by Hibernate and stored in the database.
 * References owner (User) which cannot be null at the persistence time.
 * <p>
 * StressLevel and SleepQuality are enums with the score which can be changed in {@link ch.uzh.ifi.seal.ConfigurationConstants}
 * The information from the daily form will influence the tiredness and as result the productivity of user
 * during the day in question.
 */
@Entity
@Table(name = "daily_form_info")
public class DailyFormInfo {

	// identification, generated by the database
	private int id;
	private LocalDate date; //for the date
	// information about the day which cannot be null
	private double sleepDuration;
	private SleepQuality sleepQuality;
	private StressLevel stressLevel;
	// the reference to the owner cannot be null
	private User owner;

	public DailyFormInfo() {
	}

	public DailyFormInfo(LocalDate date, double sleepDuration, SleepQuality sleepQuality, StressLevel stressLevel, User owner) {
		this.date = date;
		this.sleepDuration = sleepDuration;
		this.sleepQuality = sleepQuality;
		this.stressLevel = stressLevel;
		this.owner = owner;
	}

	@Id
	@GeneratedValue
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(nullable = false)
	public LocalDate getDate() {
		return date;
	}

	public void setDate(LocalDate date) {
		this.date = date;
	}

	@Column(nullable = false)
	public double getSleepDuration() {
		return sleepDuration;
	}

	public void setSleepDuration(double sleepDuration) {
		this.sleepDuration = sleepDuration;
	}

	@Column(nullable = false)
	public SleepQuality getSleepQuality() {
		return sleepQuality;
	}

	public void setSleepQuality(SleepQuality sleepQuality) {
		this.sleepQuality = sleepQuality;
	}

	@Column(nullable = false)
	public StressLevel getStressLevel() {
		return stressLevel;
	}

	public void setStressLevel(StressLevel stressLevel) {
		this.stressLevel = stressLevel;
	}

	@ManyToOne
	@JsonIgnore
	@JoinColumn(nullable = false)
	public User getOwner() {
		return owner;
	}

	public void setOwner(User owner) {
		this.owner = owner;
	}

	@Override
	public String toString() {
		return Objects.toStringHelper(this)
				.add("sleepDuration", sleepDuration)
				.add("sleepQuality", sleepQuality)
				.add("stressLevel", stressLevel)
				.toString();
	}
}
